name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Restore playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright- #${{ env.PLAYWRIGHT_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Format Check
        run: pnpm format:check

      - name: Test
        run: xvfb-run pnpm run test

      - name: Deploy
        if: ${{ !startsWith(github.head_ref, 'renovate/') }}
        run: pnpm --filter "app" run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Build dry build
        if: ${{ startsWith(github.head_ref, 'renovate/') }}
        run: pnpm --filter "app" run build

      - name: Cache playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright- #${{ env.PLAYWRIGHT_VERSION }}
